# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(595, 693)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbView = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbView.sizePolicy().hasHeightForWidth())
        self.lbView.setSizePolicy(sizePolicy)
        self.lbView.setMinimumSize(QtCore.QSize(0, 200))
        self.lbView.setText("")
        self.lbView.setAlignment(QtCore.Qt.AlignCenter)
        self.lbView.setObjectName("lbView")
        self.verticalLayout.addWidget(self.lbView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bnLoad = QtWidgets.QPushButton(MainWidget)
        self.bnLoad.setObjectName("bnLoad")
        self.horizontalLayout.addWidget(self.bnLoad)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(MainWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(MainWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.rbOriginal = QtWidgets.QRadioButton(MainWidget)
        self.rbOriginal.setObjectName("rbOriginal")
        self.horizontalLayout_2.addWidget(self.rbOriginal)
        self.rbThresholded = QtWidgets.QRadioButton(MainWidget)
        self.rbThresholded.setChecked(False)
        self.rbThresholded.setObjectName("rbThresholded")
        self.horizontalLayout_2.addWidget(self.rbThresholded)
        self.rbCanny = QtWidgets.QRadioButton(MainWidget)
        self.rbCanny.setChecked(False)
        self.rbCanny.setObjectName("rbCanny")
        self.horizontalLayout_2.addWidget(self.rbCanny)
        self.rbResult = QtWidgets.QRadioButton(MainWidget)
        self.rbResult.setChecked(True)
        self.rbResult.setObjectName("rbResult")
        self.horizontalLayout_2.addWidget(self.rbResult)
        self.chOnlyExternal = QtWidgets.QCheckBox(MainWidget)
        self.chOnlyExternal.setChecked(True)
        self.chOnlyExternal.setObjectName("chOnlyExternal")
        self.horizontalLayout_2.addWidget(self.chOnlyExternal)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.slSaturationFrom = QtWidgets.QSlider(MainWidget)
        self.slSaturationFrom.setMaximum(255)
        self.slSaturationFrom.setOrientation(QtCore.Qt.Horizontal)
        self.slSaturationFrom.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slSaturationFrom.setObjectName("slSaturationFrom")
        self.gridLayout_2.addWidget(self.slSaturationFrom, 1, 1, 1, 1)
        self.slHueFrom = QtWidgets.QSlider(MainWidget)
        self.slHueFrom.setMaximum(179)
        self.slHueFrom.setOrientation(QtCore.Qt.Horizontal)
        self.slHueFrom.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slHueFrom.setObjectName("slHueFrom")
        self.gridLayout_2.addWidget(self.slHueFrom, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(MainWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(MainWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.spValueFrom = QtWidgets.QSpinBox(MainWidget)
        self.spValueFrom.setObjectName("spValueFrom")
        self.gridLayout_2.addWidget(self.spValueFrom, 2, 2, 1, 1)
        self.spSaturationFrom = QtWidgets.QSpinBox(MainWidget)
        self.spSaturationFrom.setObjectName("spSaturationFrom")
        self.gridLayout_2.addWidget(self.spSaturationFrom, 1, 2, 1, 1)
        self.spHueTo = QtWidgets.QSpinBox(MainWidget)
        self.spHueTo.setObjectName("spHueTo")
        self.gridLayout_2.addWidget(self.spHueTo, 0, 5, 1, 1)
        self.spValueTo = QtWidgets.QSpinBox(MainWidget)
        self.spValueTo.setObjectName("spValueTo")
        self.gridLayout_2.addWidget(self.spValueTo, 2, 5, 1, 1)
        self.spSaturationTo = QtWidgets.QSpinBox(MainWidget)
        self.spSaturationTo.setObjectName("spSaturationTo")
        self.gridLayout_2.addWidget(self.spSaturationTo, 1, 5, 1, 1)
        self.slHueTo = QtWidgets.QSlider(MainWidget)
        self.slHueTo.setMaximum(179)
        self.slHueTo.setProperty("value", 179)
        self.slHueTo.setOrientation(QtCore.Qt.Horizontal)
        self.slHueTo.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slHueTo.setObjectName("slHueTo")
        self.gridLayout_2.addWidget(self.slHueTo, 0, 4, 1, 1)
        self.slValueTo = QtWidgets.QSlider(MainWidget)
        self.slValueTo.setMaximum(255)
        self.slValueTo.setProperty("value", 255)
        self.slValueTo.setOrientation(QtCore.Qt.Horizontal)
        self.slValueTo.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slValueTo.setObjectName("slValueTo")
        self.gridLayout_2.addWidget(self.slValueTo, 2, 4, 1, 1)
        self.spHueFrom = QtWidgets.QSpinBox(MainWidget)
        self.spHueFrom.setObjectName("spHueFrom")
        self.gridLayout_2.addWidget(self.spHueFrom, 0, 2, 1, 1)
        self.slValueFrom = QtWidgets.QSlider(MainWidget)
        self.slValueFrom.setMaximum(255)
        self.slValueFrom.setOrientation(QtCore.Qt.Horizontal)
        self.slValueFrom.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slValueFrom.setObjectName("slValueFrom")
        self.gridLayout_2.addWidget(self.slValueFrom, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(MainWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(MainWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.slSaturationTo = QtWidgets.QSlider(MainWidget)
        self.slSaturationTo.setMaximum(255)
        self.slSaturationTo.setProperty("value", 255)
        self.slSaturationTo.setOrientation(QtCore.Qt.Horizontal)
        self.slSaturationTo.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slSaturationTo.setObjectName("slSaturationTo")
        self.gridLayout_2.addWidget(self.slSaturationTo, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(MainWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(MainWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(MainWidget)
        self.slHueFrom.sliderMoved['int'].connect(self.spHueFrom.setValue)
        self.spHueFrom.valueChanged['int'].connect(self.slHueFrom.setValue)
        self.slSaturationFrom.valueChanged['int'].connect(self.spSaturationFrom.setValue)
        self.spSaturationFrom.valueChanged['int'].connect(self.slSaturationFrom.setValue)
        self.slValueFrom.sliderMoved['int'].connect(self.spValueFrom.setValue)
        self.spValueFrom.valueChanged['int'].connect(self.slValueFrom.setValue)
        self.slHueTo.sliderMoved['int'].connect(self.spHueTo.setValue)
        self.spHueTo.valueChanged['int'].connect(self.slHueTo.setValue)
        self.slSaturationTo.sliderMoved['int'].connect(self.spSaturationTo.setValue)
        self.spSaturationTo.valueChanged['int'].connect(self.slSaturationTo.setValue)
        self.slValueTo.sliderMoved['int'].connect(self.spValueTo.setValue)
        self.spValueTo.valueChanged['int'].connect(self.slValueTo.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "MainWidget"))
        self.bnLoad.setText(_translate("MainWidget", "Load"))
        self.label_4.setText(_translate("MainWidget", "Modes:"))
        self.rbOriginal.setText(_translate("MainWidget", "Original"))
        self.rbThresholded.setText(_translate("MainWidget", "Thresholded"))
        self.rbCanny.setText(_translate("MainWidget", "Canny"))
        self.rbResult.setText(_translate("MainWidget", "Result"))
        self.chOnlyExternal.setText(_translate("MainWidget", "Only external"))
        self.label_7.setText(_translate("MainWidget", "to"))
        self.label_3.setText(_translate("MainWidget", "Value"))
        self.label_2.setText(_translate("MainWidget", "Saturation"))
        self.label.setText(_translate("MainWidget", "Hue"))
        self.label_5.setText(_translate("MainWidget", "to"))
        self.label_9.setText(_translate("MainWidget", "to"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWidget = QtWidgets.QWidget()
    ui = Ui_MainWidget()
    ui.setupUi(MainWidget)
    MainWidget.show()
    sys.exit(app.exec_())

