# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Dec  4 23:44:29 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(864, 692)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 864, 21))
        self.menubar.setObjectName("menubar")
        self.menuDockWindow = QtGui.QMenu(self.menubar)
        self.menuDockWindow.setObjectName("menuDockWindow")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dock_widget_exec = QtGui.QDockWidget(MainWindow)
        self.dock_widget_exec.setObjectName("dock_widget_exec")
        self.dock_widget_exec_contents = QtGui.QWidget()
        self.dock_widget_exec_contents.setObjectName("dock_widget_exec_contents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dock_widget_exec_contents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_exec = QtGui.QPushButton(self.dock_widget_exec_contents)
        self.button_exec.setObjectName("button_exec")
        self.verticalLayout_2.addWidget(self.button_exec)
        self.container_code_editor = QtGui.QScrollArea(self.dock_widget_exec_contents)
        self.container_code_editor.setFrameShape(QtGui.QFrame.NoFrame)
        self.container_code_editor.setWidgetResizable(True)
        self.container_code_editor.setObjectName("container_code_editor")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 256, 160))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.container_code_editor.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.container_code_editor)
        self.dock_widget_exec.setWidget(self.dock_widget_exec_contents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_widget_exec)
        self.dock_widget_simple_log = QtGui.QDockWidget(MainWindow)
        self.dock_widget_simple_log.setObjectName("dock_widget_simple_log")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setContentsMargins(-1, 2, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_clear_slog = QtGui.QToolButton(self.dockWidgetContents)
        self.button_clear_slog.setObjectName("button_clear_slog")
        self.verticalLayout_3.addWidget(self.button_clear_slog)
        self.simple_log = QtGui.QPlainTextEdit(self.dockWidgetContents)
        self.simple_log.setObjectName("simple_log")
        self.verticalLayout_3.addWidget(self.simple_log)
        self.dock_widget_simple_log.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_widget_simple_log)
        self.toolBarGeneral = QtGui.QToolBar(MainWindow)
        self.toolBarGeneral.setObjectName("toolBarGeneral")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarGeneral)
        self.dock_widget_output = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock_widget_output.sizePolicy().hasHeightForWidth())
        self.dock_widget_output.setSizePolicy(sizePolicy)
        self.dock_widget_output.setObjectName("dock_widget_output")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setContentsMargins(-1, 2, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_clear_output = QtGui.QToolButton(self.dockWidgetContents_3)
        self.button_clear_output.setObjectName("button_clear_output")
        self.verticalLayout_4.addWidget(self.button_clear_output)
        self.output = QtGui.QTextEdit(self.dockWidgetContents_3)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout_4.addWidget(self.output)
        self.dock_widget_output.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dock_widget_output)
        self.menubar.addAction(self.menuDockWindow.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.button_clear_slog, QtCore.SIGNAL("clicked()"), self.simple_log.clear)
        QtCore.QObject.connect(self.button_clear_output, QtCore.SIGNAL("clicked()"), self.output.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.menuDockWindow.setTitle(QtGui.QApplication.translate("MainWindow", "Окна", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_widget_exec.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Выполнение скрипта", None, QtGui.QApplication.UnicodeUTF8))
        self.button_exec.setText(QtGui.QApplication.translate("MainWindow", "Выполнить", None, QtGui.QApplication.UnicodeUTF8))
        self.button_exec.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Return", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_widget_simple_log.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Простой лог", None, QtGui.QApplication.UnicodeUTF8))
        self.button_clear_slog.setToolTip(QtGui.QApplication.translate("MainWindow", "Очистить лог", None, QtGui.QApplication.UnicodeUTF8))
        self.button_clear_slog.setStatusTip(QtGui.QApplication.translate("MainWindow", "Очистить лог", None, QtGui.QApplication.UnicodeUTF8))
        self.button_clear_slog.setText(QtGui.QApplication.translate("MainWindow", "Очистить", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarGeneral.setWindowTitle(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_widget_output.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Вывод", None, QtGui.QApplication.UnicodeUTF8))
        self.button_clear_output.setText(QtGui.QApplication.translate("MainWindow", "Очистить", None, QtGui.QApplication.UnicodeUTF8))

