#!/usr/bin/env python3
# -*- coding: utf-8 -*-


# SOURCE: https://thispointer.com/python-check-if-a-process-is-running-by-name-and-find-its-process-id-pid/

# pip install psutil

import sys
import argparse
from get_cpu_process import get_pid, get_process_run_time, is_running

parser = argparse.ArgumentParser(
    description="Simple CPU related script written by Zac the Wise utilising psutil"
)

# set arguements
parser.add_argument(
    "--get-pid", action='store_true',
    help="returns PID of process name"
)
parser.add_argument(
    "--run-time", action='store_true',
    help="returns run time of process name"
)
parser.add_argument(
    "process_name",
    help="when used alone, returns True if process is running"
)

# parse args
args = parser.parse_args()

if args.get_pid:
    print(get_pid(provided_process_name=args.process_name))
    sys.exit()

if args.run_time:
    print(get_process_run_time(provided_process_name=args.process_name))
    sys.exit()

if args.process_name:
    print(is_running(provided_process_name=args.process_name))
    sys.exit()
